// Ordered from longest to shortest semantic motions so numeric tokens prefer
// complete motion matches before falling back to individual directions.
const MOTIONS = [
  '236236',
  '214214',
  '236',
  '214',
  '623',
  '421',
  '41236',
  '63214',
  '22',
  '66',
  '44',
  '88',
  '28',
  '82',
  '46',
  '64',
  '426',
  '624',
  '632',
  '360',
  '720',
  '1080',
];

// Human-friendly aliases are normalized before button parsing, which lets
// notations like "dp.HP" resolve as a motion followed by a button.
export const MOTION_ALIASES: Record<string, string> = {
  qcf: '236',
  quartercircleforward: '236',
  'quarter circle forward': '236',
  'quarter-circle-forward': '236',
  qcb: '214',
  quartercircleback: '214',
  'quarter circle back': '214',
  'quarter-circle-back': '214',
  dp: '623',
  dragonpunch: '623',
  'dragon punch': '623',
  'dragon-punch': '623',
  srk: '623',
  shoryuken: '623',
  rdp: '421',
  reversedp: '421',
  'reverse dp': '421',
  'reverse dragon punch': '421',
  reversedragonpunch: '421',
  hcf: '41236',
  halfcircleforward: '41236',
  'half circle forward': '41236',
  'half-circle-forward': '41236',
  hcb: '63214',
  halfcircleback: '63214',
  'half circle back': '63214',
  'half-circle-back': '63214',
  '2qcf': '236236',
  'double qcf': '236236',
  doublequartercircleforward: '236236',
  'double quarter circle forward': '236236',
  '2qcb': '214214',
  'double qcb': '214214',
  doublequartercircleback: '214214',
  'double quarter circle back': '214214',
  spd: '360',
  fullcircle: '360',
  'full circle': '360',
  'full-circle': '360',
  '360motion': '360',
  doublecircle: '720',
  'double circle': '720',
  'double-circle': '720',
  '720motion': '720',
  dd: '22',
  downdown: '22',
  'down down': '22',
  'down-down': '22',
  doubledown: '22',
  'double down': '22',
  uu: '88',
  upup: '88',
  'up up': '88',
  'up-up': '88',
  doubleup: '88',
  'double up': '88',
  ff: '66',
  forwardforward: '66',
  'forward forward': '66',
  'forward-forward': '66',
  'dash forward': '66',
  dash: '66',
  bb: '44',
  backback: '44',
  'back back': '44',
  'back-back': '44',
  backdash: '44',
  'back dash': '44',
  'tiger knee': '2369',
  tk: '2369',
  tigerknee: '2369',
  'tiger-knee': '2369',
};

export const DIRECTIONS = ['1', '2', '3', '4', '5', '6', '7', '8', '9'];

export const COMMON_BUTTONS = [
  'L',
  'M',
  'H',
  'S',
  'LP',
  'MP',
  'HP',
  'LK',
  'MK',
  'HK',
  'P',
  'K',
  'A',
  'B',
  'C',
  'D',
  'X',
  'Y',
];

export const STANCE_MODIFIERS: Record<string, string> = {
  standing: 'st.',
  stand: 'st.',
  'st.': 'st.',
  st: 'st.',
  's.': 'st.',
  crouching: 'cr.',
  crouch: 'cr.',
  'cr.': 'cr.',
  cr: 'cr.',
  'c.': 'cr.',
  jumping: 'j.',
  jump: 'j.',
  'j.': 'j.',
  j: 'j.',
  air: 'j.',
  aerial: 'j.',
  superjump: 'sj.',
  'super jump': 'sj.',
  'sj.': 'sj.',
  sj: 'sj.',
  'double jump': 'dj.',
  doublejump: 'dj.',
  'dj.': 'dj.',
  dj: 'dj.',
  'neutral jump': 'nj.',
  neutraljump: 'nj.',
  'nj.': 'nj.',
  nj: 'nj.',
  close: 'cl.',
  'cl.': 'cl.',
  cl: 'cl.',
  far: 'f.',
  'f.': 'f.',
  'b.': 'b.',
  'db.': 'db.',
  'df.': 'df.',
  'ub.': 'ub.',
  'u.': 'u.',
  'uf.': 'uf.',
  'counter hit': 'CH',
  counterhit: 'CH',
  'counter-hit': 'CH',
  ch: 'CH',
};

export const SPECIAL_MODIFIERS: Record<string, string> = {
  'tiger knee': 'tk.',
  tigerknee: 'tk.',
  'tiger-knee': 'tk.',
  'tk.': 'tk.',
  tk: 'tk.',
  'instant air dash': 'iad',
  instantairdash: 'iad',
  'instant-air-dash': 'iad',
  iad: 'iad',
  'jump cancel': 'jc.',
  jumpcancel: 'jc.',
  'jump-cancel': 'jc.',
  'jc.': 'jc.',
  jc: 'jc.',
  'super jump cancel': 'sjc.',
  superjumpcancel: 'sjc.',
  'super-jump-cancel': 'sjc.',
  'sjc.': 'sjc.',
  sjc: 'sjc.',
  'high jump cancel': 'hjc.',
  highjumpcancel: 'hjc.',
  'hjc.': 'hjc.',
  hjc: 'hjc.',
  delay: 'dl.',
  delayed: 'dl.',
  'dl.': 'dl.',
  dl: 'dl.',
  dash: 'dash',
  dashing: 'dash',
  whiff: '(whiff)',
  whiffed: '(whiff)',
  land: '|>',
  charge: '[charge]',
  charging: '[charge]',
  hold: '[hold]',
  holding: '[hold]',
  release: '[release]',
  otg: 'OTG',
  fc: 'FC',
  // Tekken 8 game-state prefixes
  'h.': 'H.',
  'r.': 'R.',
};

export const NRS_MODIFIERS: Record<string, string> = {
  air: 'AIR',
  amp: 'AMP',
  'back dash': 'BACK DASH',
  backdash: 'BACK DASH',
  block: 'Block',
  dash: 'DASH',
  delay: 'DELAY',
  delayed: 'DELAY',
  en: 'EN',
  ex: 'EX',
  fb: 'FB',
  grab: 'Grab',
  j: 'J',
  jb: 'JB',
  jf: 'JF',
  jik: 'JIK',
  jip: 'JIP',
  ji: 'JI',
  kb: 'KB',
  md: 'MD',
  mb: 'MB',
  njk: 'NJK',
  njp: 'NJP',
  pb: 'PB',
  rc: 'RC',
  run: 'RUN',
  sh: 'SH',
  interactable: 'Interactable',
  trait: 'Trait',
  throw: 'Throw',
};

export const NRS_PARENTHETICALS: Readonly<Record<string, string>> = {
  hold: '(hold)',
  swapside: '(swap side)',
  air: 'AIR',
  delay: 'DELAY',
};

export const TEKKEN_MODIFIERS: Record<string, string> = {
  air: 'AIR',
  any: 'any',
  iws: 'iWS',
  'instant while standing': 'iWS',
  iwr: 'iWR',
  'instant while running': 'iWR',
  cc: 'cc',
  'crouch cancel': 'cc',
  cd: 'cd',
  'crouch dash': 'cd',
  lp: 'LP',
  'low parry': 'LP',
  wgf: 'WGF',
  tgf: 'TGF',
  ewgf: 'EWGF',
  otgf: 'OTGF',
  etgf: 'ETGF',
  'during heat': 'During Heat',
  'heat burst': 'Heat Burst',
  'heat smash': 'Heat Smash',
  'rage art': 'Rage Art',
  cl: 'CL',
  otg: 'OTG',
  jg: 'JG',
  knd: 'KND',
  p: 'P',
  j: 'J',
  h: 'H',
  r: 'R',
};

export const SEPARATORS = [
  '►',
  '|>',
  '>',
  '→',
  ',',
  '+',
  '~',
  ':',
  '=',
  '_',
  '<',
  '»',
  '/\\',
  '#',
  '.',
  'xx',
  'or',
  'link',
  'linked',
  '/',
];

// Sorted longest-first so 'd/f' is tried before 'd' (greedy match).
export const LETTER_DIR_COMPOUNDS = [
  'u/f',
  'd/f',
  'u/b',
  'd/b',
  'uf',
  'df',
  'ub',
  'db',
];
export const NRS_LETTER_DIR_COMPOUNDS = LETTER_DIR_COMPOUNDS.filter(
  (direction) => direction.includes('/'),
);
export const LETTER_DIR_CARDINALS = ['n', 'f', 'b', 'u', 'd'];
export const TEKKEN_MECHANICS: Record<string, string> = {
  '*(max)': '*(max)',
  'wbl!': 'WBl!',
  'wbo!': 'WBo!',
  'fbl!': 'FBl!',
  'wb!': 'WB!',
  'bb!': 'BB!',
  'w!': 'W!',
  'f!': 'F!',
  's!': 'S!',
  't!': 'T!',
  'b!': 'B!',
  'fb!': 'FB!',
  '*': '*',
};
export const SORTED_TEKKEN_MECHANICS = Object.keys(TEKKEN_MECHANICS).sort(
  (a, b) => b.length - a.length,
);
// Common Tekken stance/state tokens mapped to their canonical display form.
export const LETTER_DIR_STANCES: Record<string, string> = {
  swl: 'SWL',
  swr: 'SWR',
  ssl: 'SSL',
  ssr: 'SSR',
  ss: 'SS',
  ws: 'WS',
  fc: 'FC',
  wr: 'WR',
  bt: 'BT',
  hfc: 'hFC',
  sw: 'SW',
};
export const SORTED_LETTER_DIR_STANCES = Object.keys(LETTER_DIR_STANCES).sort(
  (a, b) => b.length - a.length,
);

// Pre-sorted lookup tables keep the parser's hot path allocation-free.
export const SORTED_ALL_MODIFIERS = Object.keys({
  ...STANCE_MODIFIERS,
  ...SPECIAL_MODIFIERS,
}).sort((a, b) => b.length - a.length);
export const SORTED_NRS_MODIFIERS = Object.keys(NRS_MODIFIERS).sort(
  (a, b) => b.length - a.length,
);
export const SORTED_TEKKEN_MODIFIERS = Object.keys(TEKKEN_MODIFIERS).sort(
  (a, b) => b.length - a.length,
);
export const MULTI_STEP_ALIASES: Record<
  string,
  Array<{ type: 'motion' | 'direction'; value: string }>
> = {
  hcbf: [
    { type: 'motion', value: '63214' },
    { type: 'direction', value: '6' },
  ],
  halfcirclebackforward: [
    { type: 'motion', value: '63214' },
    { type: 'direction', value: '6' },
  ],
  'half circle back forward': [
    { type: 'motion', value: '63214' },
    { type: 'direction', value: '6' },
  ],
  'half-circle-back-forward': [
    { type: 'motion', value: '63214' },
    { type: 'direction', value: '6' },
  ],
};
export const SORTED_ALL_ALIASES = [
  ...Object.keys(MOTION_ALIASES),
  ...Object.keys(MULTI_STEP_ALIASES),
].sort((a, b) => b.length - a.length);
export const SORTED_MOTIONS = [...MOTIONS].sort((a, b) => b.length - a.length);
